userss/app/users/models.py
from app import db
from app.users import constants as USER

class User(db.Model):

      __tablename__ = 'users_user'
      id = db.Column(db.Integer, primary_key=True)
      name = db.Column(db.String(50), unique=True)
      email = db.Column(db.String(120), unique=True)
      password = db.Column(db.String(120))
      role = db.Column(db.SmallInteger, default=USER.USER)
      status = db.Column(db.SmallInteger, default=USER.NEW)

      def __init__(self, name=None, email=None, password=None):
        self.name = name
        self.email = email
        self.password = password

      def getStatus(self):
        return USER.STATUS[self.status]

      def getRole(self):
        return USER.ROLE[self.role]

      def __repr__(self):
          return '<User %r>' % (self.name)

userss/app/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email

class LoginForm(Form):
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])

class RegisterForm(Form):
  name = TextField('NickName', [Required()])
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])
  confirm = PasswordField('Repeat Password', [
        Required(),
        EqualTo('password', message='Passwords must match')
        ])
  accept_tos = BooleanField('I accept the TOS', [Required()])
  recaptcha = RecaptchaField()

userss/app/__init__.py
from flask import Flask, render_template
from flask.ext.sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from app.users.views import mod as usersModule
app.register_blueprint(usersModule)

  # Later on you'll import the other blueprints the same way:
  #from app.comments.views import mod as commentsModule
  #from app.posts.views import mod as postsModule
  #app.register_blueprint(commentsModule)
  #app.register_blueprint(postsModule)

userss/app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.route('/me/')
@requires_login
def home():
  return render_template("users/profile.html", user=g.user)

@mod.before_request
def before_request():
  """
  pull user's profile from the database before every request are treated
  """
  g.user = None
  if 'user_id' in session:
    g.user = User.query.get(session['user_id'])

@mod.route('/login/', methods=['GET', 'POST'])
def login():
  """
  Login form
  """
  form = LoginForm(request.form)
  # make sure data are valid, but doesn't validate password is right
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    # we use werzeug to validate user's password
    if user and check_password_hash(user.password, form.password.data):
      # the session can't be modified as it's signed, 
      # it's a safe place to store the user id
      session['user_id'] = user.id
      flash('Welcome %s' % user.name)
      return redirect(url_for('users.home'))
    flash('Wrong email or password', 'error-message')
  return render_template("users/login.html", form=form)

@mod.route('/register/', methods=['GET', 'POST'])
def register():
  """
  Registration Form
  """
  form = RegisterForm(request.form)
  if form.validate_on_submit():
    # create an user instance not yet stored in the database
    user = User(name=form.name.data, email=form.email.data, \
      password=generate_password_hash(form.password.data))
    # Insert the record in our database and commit it
    db.session.add(user)
    db.session.commit()

    # Log the user in, as he now has an id
    session['user_id'] = user.id

    # flash will display a message to the user
    flash('Thanks for registering')
    # redirect user to the 'home' method of the user module.
    return redirect(url_for('users.home'))
  return render_template("users/register.html", form=form)

userss/app/templates/base.html
<html>
    <head>
      <title>{% block title %}My Site{% endblock %}</title>
      {% block css %}
      <link rel="stylesheet" href="/static/css/reset-min.css" />
      <link rel="stylesheet" href="/static/css/main.css" />
      {% endblock %}
      {% block script %}
      <script src="/static/js/main.js" type="text/javascript"></script>
      {% endblock %}
    </head>
    <body>
      <div id="header">{% block header %}{% endblock %}</div>
      <div id="messages-wrap">
        <div id="messages">
          {% for category, msg in get_flashed_messages(with_categories=true) %}
            <p class="message flash-{{ category }}">{{ msg }}</p>
          {% endfor %}
        </div>
      </div>
      <div id="content">{% block content %}{% endblock %}</div>
      <div id="footer">{% block footer %}{% endblock %}</div>
    </body>
  </html>

userss/app/templates/forms/macros.html
{% macro render_field(field) %}
      <div class="form_field">
      {{ field.label(class="label") }}
      {% if field.errors %}
          {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
          {{ field(class=css_class, **kwargs) }}
          <ul class="errors">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
      {% else %}
          {{ field(**kwargs) }}
      {% endif %}
      </div>
  {% endmacro %}

userss/app/templates/users/login.html
{% extends "base.html" %}
  {% block content %}
    {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      <input type="submit" value="Login" class="button green">
    </form>
    <a href="{{ url_for('users.register') }}">Register</a>
  {% endblock %}

userss/app/templates/users/register.html
{% extends "base.html" %}
  {% block content %}
    {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.name, class="input text") }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      {{ render_field(form.confirm, class="input text") }}
      {{ render_field(form.accept_tos, class="input checkbox") }}
      <label>ReCaptcha</label>
      {{ form.recaptcha }}
      <input type="submit" value="Register" class="button green">
    </form>
    <a href="{{ url_for('users.login') }}">Login</a>
  {% endblock %}