oldasof2:8:2014/app/users/models.py
from app import db
from app.users import constants as USER


class User(db.Model):

    __tablename__ = 'users_user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(120))
    role = db.Column(db.SmallInteger, default=USER.USER)
    status = db.Column(db.SmallInteger, default=USER.NEW)
    rating = db.Column(db.Integer, server_default="0")

    def __init__(self, name=None, email=None, password=None):
        self.name = name
        self.email = email
        self.password = password

    def getStatus(self):
        return USER.STATUS[self.status]

    def getRole(self):
        return USER.ROLE[self.role]

    def __repr__(self):
        return '<User %r>' % (self.name)


class Debates(db.Model):

    __tablename__ = 'users_debates'
    did = db.Column(db.Integer, primary_key=True)
    id = db.Column(db.Integer)
    title = db.Column(db.Text())
    text = db.Column(db.Text())
    sidea = db.Column(db.Text())
    sideb = db.Column(db.Text())
    rating = db.Column(db.Integer, server_default="0")


class Arguments(db.Model):

    __tablename__ = 'users_arguments'
    aid = db.Column(db.Integer, primary_key=True)
    did = db.Column(db.Integer)
    id = db.Column(db.Integer)
    side = db.Column(db.Integer)
    argument = db.Column(db.Text())
    rating = db.Column(db.Integer, server_default="0")

oldasof2:8:2014/app/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email


class LoginForm(Form):
    email = TextField('Enter email', [Required(), Email()])
    password = PasswordField('Password', [Required()])


class RegisterForm(Form):
    name = TextField('NickName', [Required()])
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])
    confirm = PasswordField('Repeat Password', [
        Required(),
        EqualTo('password', message='Passwords must match')
    ])
    accept_tos = BooleanField('I accept the TOS', [Required()])
    recaptcha = RecaptchaField()

oldasof2:8:2014/app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login

mod = Blueprint('users', __name__, url_prefix='')


@mod.route('/me/')
@requires_login
def home():
    return render_template("users/profile.html", user=g.user)


# @mod.before_request
# def before_request():
# @mod.teardown_request
# def teardown_request(exception):
#     db = getattr(g, 'db', None)
#     if db is not None:
#         db.close()
@mod.before_request
def before_request():
    g.db = db
    """
  pull user's profile from the database before every request are treated
  """
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])


@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # create an user instance not yet stored in the database
        user = User(name=form.name.data, email=form.email.data,
                    password=generate_password_hash(form.password.data))
        # Insert the record in our database and commit it
        db.session.add(user)
        db.session.commit()

        # Log the user in, as he now has an id
        session['user_id'] = user.id
        session['logged_in'] = True
        # flash will display a message to the user
        flash('Thanks for registering')
        # redirect user to the 'home' method of the user module.
        return redirect(url_for('users.show_entries'))
    return render_template("users/register.html", form=form)


@mod.route('/updebate/<int:entries_did>')
def up_vote(entries_did):
    connection = g.db.session.connection()
    g.db.engine.execute(
        'update users_user set rating = rating + 1 where id in (select id from users_debates where users_debates.did ="{0}")'.format(entries_did))
    g.db.engine.execute(
        'update users_debates set rating = rating + 1 where did = "{0}"'.format(entries_did))
    # g.db.commit()
    return redirect(request.referrer)


@mod.route('/downdebate/<int:entries_did>')
def down_vote(entries_did):
    connection = g.db.session.connection()
    g.db.engine.execute(
        'update users_user set rating = rating - 1 where id in (select id from users_debates where users_debates.did ="{0}")'.format(entries_did))
    g.db.engine.execute(
        'update users_debates set rating = rating - 1 where did = "{0}"'.format(entries_did))
    # g.db.commit()
    return redirect(request.referrer)


@mod.route('/upargument/<int:argumentsidea_aid>')
def up_argument(argumentsidea_aid):
    connection = g.db.session.connection()
    g.db.engine.execute(
        'update users_user set rating = rating + 1 where id in (select id from users_arguments where users_arguments.aid ="{0}")'.format(argumentsidea_aid))
    g.db.engine.execute(
        'update users_arguments set rating = rating + 1 where aid = "{0}"'.format(argumentsidea_aid))
    # g.db.commit()
    return redirect(request.referrer)


@mod.route('/downargument/<int:argumentsideb_aid>')
def down_argument(argumentsideb_aid):
    connection = g.db.session.connection()
    g.db.engine.execute(
        'update users_user set rating = rating - 1 where id in (select id from users_arguments where users_arguments.aid ="{0}")'.format(argumentsideb_aid))
    g.db.engine.execute(
        'update users_arguments set rating = rating - 1 where aid = "{0}"'.format(argumentsideb_aid))
    # g.db.commit()
    return redirect(request.referrer)


@mod.route('/', methods=['GET', 'POST'])
def landing_page():
    if session.get('logged_in'):
        return redirect(url_for('users.show_entries'))

    if not session.get('logged_in'):
        """
    Login form
    """
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            session['user_id'] = user.id
            session['logged_in'] = True
            flash('Welcome %s' % user.name)
            return redirect(url_for('users.show_entries'))
        flash('Wrong email or password', 'error-message')
    return (
            render_template(
                'base.html', form=form)
            )


@mod.route('/home')
def show_entries():
    connection = g.db.session.connection()
    cur = g.db.engine.execute(
        'select users_debates.did, users_debates.title, users_debates.text, users_debates.rating, users_user.name from users_debates, users_user where users_debates.id = users_user.id order by users_debates.rating desc')
    db_result = cur.fetchall()
    entries = [dict(did=row[0], title=row[1], text=row[2], rating=row[3], name=row[4])
               for row in db_result]
    currie = g.db.engine.execute(
        'select name, rating from users_user order by rating desc')
    dby_result = currie.fetchall()
    entriegard = [dict(name=row[0], rating=row[1]) for row in dby_result]
    return (
        render_template(
            'users/show_entries.html',
            entries=entries,
            entriegard=entriegard)
    )


@mod.route('/add', methods=['POST'])
def add_entry():
    connection = g.db.session.connection()
    g.db.engine.execute(
        'insert into users_debates (id, title, text, sidea, sideb) values (?, ?, ?, ?, ?)',
        [session['user_id'], request.form['title'], request.form['text'], request.form['sidea'], request.form['sideb']])
    flash('New entry was successfully posted')
    return redirect(url_for('users.show_entries'))


@mod.route('/adda', methods=['POST'])
def add_argumenta():
    connection = g.db.session.connection()
    g.db.engine.execute(
        'insert into users_arguments (did, id, argument, side) values (?, ?, ?, ?)',
        [request.form['did'], session['user_id'], request.form['argument'], request.form['side']])
    flash('New argument was successfully posted')
    return redirect(request.referrer)


@mod.route('/addb', methods=['POST'])
def add_argumentb():
    connection = g.db.session.connection()
    g.db.engine.execute(
        'insert into users_arguments (did, id, argument, side) values (?, ?, ?, ?)',
        [request.form['did'], session['user_id'], request.form['argument'], request.form['side']])
    flash('New argument was successfully posted')
    return redirect(request.referrer)


@mod.route('/debate/<int:entries_did>')
def debate_page(entries_did):
    connection = g.db.session.connection()
    query = 'select title, text, sidea, sideb, did from users_debates where did = "{0}"'.format(
        entries_did)
    cur = g.db.engine.execute(query)
    db_result = cur.fetchall()
    entries = [dict(title=row[0], text=row[1], sidea=row[2], sideb=row[3], did=row[4])
               for row in db_result]
    querytwo = 'select argument, aid, rating from users_arguments where did = "{0}" and side = "0" order by rating desc'.format(
        entries_did)
    cuv = g.db.engine.execute(querytwo)
    db_resultr = cuv.fetchall()
    argumentsidea = [dict(argument=row[0], aid=row[1], rating=row[2])
                     for row in db_resultr]
    querythree = 'select argument, aid, rating from users_arguments where did = "{0}" and side = "1" order by rating desc'.format(
        entries_did)
    cuv = g.db.engine.execute(querythree)
    db_resultq = cuv.fetchall()
    argumentsideb = [dict(argument=row[0], aid=row[1], rating=row[2])
                     for row in db_resultq]
    return (
        render_template(
            'users/debate_page.html',
            entries=entries,
            argumentsidea=argumentsidea,
            argumentsideb=argumentsideb)
    )


@mod.route('/createdebate')
def createdebate():
    return render_template('users/createdebate.html')


@mod.route('/createuser')
def createuser():
    return render_template('users/createuser.html')


@mod.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('You were logged out')
    form = LoginForm(request.form)
    return (
        render_template(
            'base.html', form=form
            )
    )

oldasof2:8:2014/app/templates/users/createdebate.html
<title>State of Debate</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
{% if session.logged_in %}
<div class=page>
  <h1>Create A Debate</h1>
  <div class=metanav>
    <a href="{{ url_for('users.show_entries') }}">back</a>
  </div>
<form action="{{ url_for('users.add_entry') }}" method=post class=add-entry>
      <dl>
        <dt>Title of debate:
        <dd><input type=text size=30 name=title>
        <dt>Debate:
        <dd><textarea name=text rows=5 cols=40></textarea>
        <dt>Side A:
        <dd><input type=text size=30 name=sidea>
        <dt>Side B:
        <dd><input type=text size=30 name=sideb>  
        <dd><input type=submit value=Share>
      </dl>
    </form>
{% endif %}

oldasof2:8:2014/app/templates/users/debate_page.html
<title>State of Debate</title>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
{% if session.logged_in %}
<div class=page>
  {% for entry in entries %}
      <h1>{{ entry.title }}</h1>
    {% endfor %}
  <div class=metanav>
    <a href="{{ url_for('users.show_entries') }}">back</a>
  </div>
  <div class=debate>
    <div class=debatetext>
          {% for entry in entries %}
          {{ entry.text|safe }}
    </div>
    <div class=debatesides>
      <div class=debatesidea>
      <h2>{{ entry.sidea }}</h2>
      </div>
      <div class=debatesideb>
        <h2>{{ entry.sideb }}</h2>
      {% endfor %}
    </div>
    </div>

    <div class=argumentgen>
      <div class=argumentgensidea>
{% for entry in entries %}
<form action="{{ url_for('users.add_argumenta') }}" method=post class=add-entry>
      <dl>
        <dt>Argument Side A:
        <dd><textarea name=argument rows=5 cols=40></textarea>
        <input type=hidden name=did value={{ entry.did }}>
        <input type=hidden name=side value=0>
        <dd><input type=submit value=Share>
      </dl>
    </form>
      </div>
      <div class=argumentgensideb>
<form action="{{ url_for('users.add_argumentb') }}" method=post class=add-entry>
      <dl>
        <dt>Argument Side B:
        <dd><textarea name=argument rows=5 cols=40></textarea>
        <input type=hidden name=did value={{ entry.did }}>
        <input type=hidden name=side value=1>
        <dd><input type=submit value=Share>
      </dl>
    </form>
      </div>
{% endfor %}
    </div>

    <div class=arguments>



        <ul class=entries>
        {% for argumentz in argumentsidea %}
        <div class=asidea>
        <li><a href="/upargument/{{ argumentz.aid }}" style="text-decoration:none; color:orange;">&#11014;</a>{{ argumentz.rating }}<a href="/downargument/{{ argumentz.aid }}" style="text-decoration:none; color:orange;">&#11015;</a>{{ argumentz.argument }}
        {% endfor %}
      </ul>
      </div>
      <div class=asideb>
        <ul class=entries>
        {% for argumentz in argumentsideb %}
        <li><a href="/upargument/{{ argumentz.aid }}" style="text-decoration:none; color:orange;">&#11014;</a>{{ argumentz.rating }}<a href="/downargument/{{ argumentz.aid }}" style="text-decoration:none; color:orange;">&#11015;</a>{{ argumentz.argument }}
        {% endfor %}
      </ul>
      </div>



  </div>
{% endif %}

oldasof2:8:2014/app/templates/users/login.html
<div class=page>
    {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      <input type="submit" value="Login" class="button green">
    </form>
    <a href="{{ url_for('users.register') }}">Register</a>
</div>

oldasof2:8:2014/app/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
   Hi {{ user.name }}!
{% endblock %}

oldasof2:8:2014/app/templates/users/register.html
<div class=page>
  {% from "forms/macros.html" import render_field %}
    <form method="POST" action="." class="form">
      {{ form.csrf_token }}
      {{ render_field(form.name, class="input text") }}
      {{ render_field(form.email, class="input text") }}
      {{ render_field(form.password, class="input text") }}
      {{ render_field(form.confirm, class="input text") }}
      {{ render_field(form.accept_tos, class="input checkbox") }}
      <label>ReCaptcha</label>
      {{ form.recaptcha }}
      <input type="submit" value="Register" class="button green">
    </form>
    <a href="{{ url_for('users.login') }}">Login</a>
</div>

oldasof2:8:2014/app/templates/users/show_entries.html
{% if session['logged_in'] %}
<html>
<head>
{% block css %}
      <link rel="stylesheet" type='text/css' href="/static/css/style.show.entries.css" />
      {% endblock %}
{% block script %}
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
      <script src="/static/js/bootstrap.js" type="text/javascript"</script>
      <script src="/static/js/bootstrap.min.js" type="text/javascript"</script>
      <script src="/static/js/main.js" type="text/javascript"></script>
      {% endblock %}
    </head>
    <body>
        <div id="header">


            <nav class="navbar navbar-default" role="navigation">
                <div class="wrapeer">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="sodsymbol">
    <img border="0" src="/static/images/s.png" alt="State of Debate" width="41" height="40">
</div>
    <!-- <a class="navbar-brand" href="#">Brand</a> -->
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <form class="navbar-form navbar-left" role="search">
      <div class="container">
    <div class="row">
           <div id="custom-search-input">
      <div class="input-group">
                                <input type="text" class="  search-query form-control" placeholder="Search" />
                                <span class="input-group-btn">
                                    <button class="btn btn-danger" type="button">
                                        <span class=" glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                            </div>

                        </div>
                    </div>
    </form>
      <ul class="nav navbar-nav navbar-right">
      <li class="friendrequestblue"><img border="0" src="/static/images/friendrequestblue.png" alt="State of Debate" width="27" height="27"></li>
      <li class="messageblue"><img border="0" src="/static/images/messageblue.png" alt="State of Debate" width="27" height="27"></li>
      <li class="worldisblue"><img border="0" src="/static/images/worldisblue.png" alt="State of Debate" width="27" height="27"></li>
      <li class="home"><a href="#">Home</a></li>
      <li class="username"><a href="#">U.N.</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img border="0" src="/static/images/wheeliedeal.png" alt="State of Debate" width="13" height="13"> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<!--





    </div>

</div> -->

</div>
          </div>





<div class=page>
  <h1>Debate List</h1>
  <div class=metanav>

    <a href="{{ url_for('users.createdebate') }}">Create A Debate</a>
  </div>
  {% for message in get_flashed_messages() %}
    <div class=flash>{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
  {% block body %}{% endblock %}




{% for fuckyea in entriegard %}
<li>
{{ fuckyea.name }} {{ fuckyea.rating }}
</li>
{% endfor %}
<ul class=entries>
  {% for entry in entries %}
    <li><h2>
    	<a href="/updebate/{{ entry.did }}" style="text-decoration:none; color:orange;">&#11014;</a>{{ entry.rating }}<a href="/downdebate/{{ entry.did }}" style="text-decoration:none; color:orange;">&#11015;</a><a href="/debate/{{ entry.did }}">{{ entry.title }}</a></h2>{{ entry.text|safe }}

    	CREATED BY: {{ entry.name }}
  {% else %}
    <li><em>Unbelievable.  No entries here so far</em>
  {% endfor %}
  </ul>
  {% endif %}

</div>
</body>
</html>